### ISSUE TITLE
Frontend for Find Assay Target

### ISSUE THREAD

**Issue by aniketfadia96** [uw-ssec/neglected-diagnostics#39]
This issue tracks the development of Streamlit frontend for the `Find Assay Target` feature.

**Comment by misa-winters** [comment]
Text edits requests:

1. Change “Off-Target Sequences” to “Upload Off-Target Sequences”
2. Change the (?) bubble for both “Upload FASTA files” to: “Only single FASTA or non-aligned multi-FASTA files are allowed”
3. Change the (?) bubble for “Select Reference Sequence” to: “If no selection is made, the first file in the Target sequences will be used as the reference sequence.”

**Comment by misa-winters** [comment]
Please add the QuickGuide (it doesn't copy/paste into this comment box correctly) to the top of the page which can be found under the Find Assay Target Area section of the google doc file called [VISS_Draft text for Streamlit App](https://docs.google.com/document/d/1MPa6LWB9_AL6lxkU4QUUeInoF6jx0AWC5vRSlLlGDlE/edit?usp=sharing).
