### ISSUE TITLE
Add QuickGuide to Sequence Search

### ISSUE THREAD

**Issue by misa-winters** [uw-ssec/neglected-diagnostics#61]

**Comment by misa-winters** [comment]
**QuickGuide**

1. Select the database option from the dropdown. _Only "nucleotide" is currently supported_.
2. Enter search terms such as taxonomic group or gene in the [Enter the search term] box.
3. Click the [Submit] button.
4. _Optional Filtering_ 
       a. Click on the menu icon next to each column header in the table to apply simple filters. Maximum of two filters per column.
       b. Click the [Add filters] check box to display a second table where more sophisticated filters can be applied to the search results. Choose one or more options from the [Filter results table] dropdown to select which column(s) to apply a filter. Type, or select the filter value(s) for each column in the appropriate box.
9. Click on [Prepare Download].
WARNING - whole genome sequences or complete genomes will exceed the download size limit of the web app. Filter these out before proceeding.
11. Select the download option from the dropdown.
      a. Select [Download sequences as a fasta file] to retrieve the target area sequences only.
      b. Select [Download as CSV] to retrieve the result table displayed above.
13. Click on [Download].

**Comment by misa-winters** [comment]
Also change the "Filter dataframe on" text to "Filter results table"

**Comment by RashmikaReddy** [comment]
Changes are done!
