### ISSUE TITLE
Final text edits

### ISSUE THREAD

**Issue by misa-winters** [uw-ssec/neglected-diagnostics#85]
Under the Sequence Search tab, replace "Neglected Diagnostics: Democratizing Genetic Testing!" with "Search and Retrieve Sequences"

Replace all instances of "Find Assay Target Area" with "Find Assay Design Area" so that the nomenclature isn't confusing.

1. Left Navigation Tab
2. Home tab, two locations - line 7 under "Sequence to Diagnostic Pipeline", and the "Find Assay Target Area" header
4. Find Assay Target Area Tab - Parameter section (6 changes)
    Replace "Target Area Parameters" section header with "Assay Design Area Parameters"   
    Replace "Enter the target region size (# of base pairs)" with "Enter the assay design region size (# of base pairs)"
    Replace "Enter the target region slide size (# of base pairs)" with "Enter the assay design region slide size (# of base pairs)"
    Replace "Enter the maximum differences allowed between primer and target sequences" with "Enter the maximum differences allowed between assay area and target sequences"
    Replace "Enter the maximum differences allowed between primer and off-target sequences" with "Enter the maximum differences allowed between assay area and off-target sequences"
    Replace [Find Target Area] button with [Find Assay Design Area]
5. Find Assay Target Area Tab -  replace QuickGuide with the updated version below

**QuickGuide**

1. Drag and drop, or Click on the [Browse files] button to choose and upload the individual sequence files or non-aligned multiple sequence files (FASTA or FAS)  for the Assay Target(s). _These are the sequences that the assay should be able to detect._
2. Drag and drop, or Click on the [Browse files] button to choose and upload the individual sequence files or non-aligned multiple sequence files (FASTA or FAS) for the Assay Off-Target(s). _These are the sequences that the assay should not be able to detect._
3. Input Assay Design Area Parameters
    a. From the set of sequences included in the Target sequences, choose one to be the reference sequence. Input the sequence header (not the name of the file) under [Select Reference Sequence]. 
    b. Enter a number into the [assay design region size] box, or use the +/- symbols to adjust the default number. _This should be equal to or larger than the intended fragment size for the assay. It is the total area where targets and off targets will be compared._
    c. Enter a number into the [assay design region slide size] box, or use the +/- symbols to adjust the default number. _This designates the shift in base pair distance between each design area along the total sequence length which is defined by the reference sequence._
    d. Enter a number into the [maximum differences allowed between assay area and target sequences] box, or use the +/- symbols to adjust the default number. _This controls the calculated average differences between the target sequences and the assay design area candidates._
    e. Enter a number into the [maximum differences allowed between assay area and off-target sequences] box, or use the +/- symbols to adjust the default number. _This controls the calculated average differences between the off-target sequences and the assay design area candidates._
4. Click on the [Find Assay Design Area] button to run the process. _Note that large files, small target region sizes or a combination of both will require more processing time._ 
5. Select the download option from the dropdown 
    a. Select [Download as CSV] to retrieve the result table displayed above
    b. Select [Download sequences as a fasta file] to retrieve the assay design area sequences only.
6. Click on the [Download] button.

**Comment by acefgin** [comment]
Addressed with PR #86
