### ISSUE TITLE
Fasta file formatting incorrect for Find Assay Design Area

### ISSUE THREAD

**Issue by misa-winters** [uw-ssec/neglected-diagnostics#87]
Something got wonky with the latest update and the downloaded fasta file needs a small tweak.

There needs to be a ">" before every sequence header or it won't be read correctly. 
For example 
>Assay_Design_Area_3
ACCTTAATTAAGCTGTAAAAAGCCATAATTAAAACTAAGCCAAACTACGAAAGTGACTTTAATATGATCCAATCACACGACAGCTAAGATCCAAACTGGG
>Assay_Design_Area_11
CTTATATTAGTAACTGATAGTATACTAATAATTAACAGCAAATAAATAAAACCCAACACTAAATTATTTATTAAGACACTGTTAACCCAACACAGGCGTGCA

**Comment by carlosgjs** [comment]
I'll fix it!
